region                    = "europe-west3"
environment               = "dev"
service_name              = "hygraph-showcase-dev"
domain                    = "hygraph-showcase-dev.shekeyweb.com"
enable_dns                = false
enable_cdn                = false
enable_armor              = false
enable_load_balancer      = false
ingress_mode              = "INGRESS_TRAFFIC_ALL"
github_org                = "Shekey"
github_repo               = "hygraph-grafana-showscase"
github_branches           = ["refs/heads/main", "refs/heads/develop"]
cloud_run_min_instances   = 0
cloud_run_max_instances   = 2
cloud_run_concurrency     = 40
cloud_run_cpu             = "1"
cloud_run_memory          = "256Mi"
cloud_run_timeout_seconds = 30
